import { Router } from "express";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import multer from "multer";
import { z } from "zod";
import { Song } from "../models/song.models.js";
import { Album } from "../models/album.models.js";
import { Artist } from "../models/artist.models.js";
import { Playlist } from "../models/playlist.models.js";
import { Like } from "../models/like.models.js";
import { RecentlyPlayed } from "../models/recentlyPlayed.models.js";
import { User } from "../models/user.models.js";
import { asyncHandler, fail, ok, pagination } from "../utils/api.js";
import { requireAdmin, requireAuth } from "../middleware/jwt.middleware.js";
import cloudinary from "../lib/cludinary.js";

const router = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 }, fileFilter: (_req, file, cb) => cb(null, /^(audio|image)\//.test(file.mimetype)) });
const parse = (schema, value) => { const result = schema.safeParse(value); if (!result.success) throw fail(422, result.error.issues.map(issue => issue.message).join(", ")); return result.data; };
const token = (user) => jwt.sign({ sub: user._id.toString(), role: user.role }, process.env.JWT_SECRET, { expiresIn: process.env.JWT_EXPIRES_IN || "7d" });
const safeUser = (user) => ({ id: user._id, name: user.fullName, email: user.email, avatar: user.imageUrl, role: user.role });
const authSchema = z.object({ name: z.string().trim().min(2).max(80), email: z.string().email().transform(value => value.toLowerCase()), password: z.string().min(8).max(128), confirmPassword: z.string() });
const loginSchema = z.object({ email: z.string().email().transform(value => value.toLowerCase()), password: z.string().min(1) });
const songSchema = z.object({ title: z.string().trim().min(1).max(160), artist: z.string().trim().min(1).max(120), imageUrl: z.string().url(), audioUrl: z.string().url(), duration: z.coerce.number().nonnegative(), albumId: z.string().optional().nullable(), genre: z.string().max(60).optional(), isExplicit: z.boolean().optional() });
const playlistSchema = z.object({ name: z.string().trim().min(1).max(100), description: z.string().max(500).optional(), coverImage: z.string().url().optional(), isPublic: z.boolean().optional() });
const ownerOrAdmin = (playlist, user) => playlist.owner.toString() === user._id.toString() || user.role === "admin";
const recordHistory = async (userId, songId) => { await RecentlyPlayed.findOneAndUpdate({ user: userId, song: songId }, { playedAt: new Date() }, { upsert: true, new: true }); const excess = await RecentlyPlayed.find({ user: userId }).sort({ playedAt: -1 }).skip(50).select("_id"); if (excess.length) await RecentlyPlayed.deleteMany({ _id: { $in: excess } }); };
const uploadBuffer = (file) => new Promise((resolve, reject) => cloudinary.uploader.upload_stream({ resource_type: file.mimetype.startsWith("audio/") ? "video" : "image" }, (error, result) => error ? reject(error) : resolve(result)).end(file.buffer));

router.post("/auth/register", asyncHandler(async (req, res) => { const body = parse(authSchema, req.body); if (body.password !== body.confirmPassword) throw fail(422, "Passwords do not match"); if (await User.exists({ email: body.email })) throw fail(409, "An account with this email already exists"); const user = await User.create({ fullName: body.name, email: body.email, password: await bcrypt.hash(body.password, 12) }); const jwtToken = token(user); res.cookie("token", jwtToken, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 7 * 24 * 60 * 60 * 1000 }); ok(res, { user: safeUser(user), token: jwtToken }, "Account created", 201); }));
router.post("/auth/login", asyncHandler(async (req, res) => { const body = parse(loginSchema, req.body); const user = await User.findOne({ email: body.email }).select("+password"); if (!user?.password || !(await bcrypt.compare(body.password, user.password))) throw fail(401, "Invalid email or password"); const jwtToken = token(user); res.cookie("token", jwtToken, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 7 * 24 * 60 * 60 * 1000 }); ok(res, { user: safeUser(user), token: jwtToken }, "Logged in"); }));
router.post("/auth/logout", (_req, res) => { res.clearCookie("token"); ok(res, null, "Logged out"); });
router.get("/auth/me", requireAuth, (req, res) => ok(res, safeUser(req.user), "Authenticated user"));

router.get("/songs", asyncHandler(async (req, res) => { const { page, limit, skip } = pagination(req.query); const filter = {}; if (req.query.q) filter.$text = { $search: req.query.q }; for (const key of ["artist", "albumId", "genre"]) if (req.query[key]) filter[key] = req.query[key]; const [songs, total] = await Promise.all([Song.find(filter).sort(req.query.q ? { score: { $meta: "textScore" } } : { createdAt: -1 }).skip(skip).limit(limit), Song.countDocuments(filter)]); ok(res, songs, "Songs fetched", 200, { pagination: { page, limit, total, totalPages: Math.ceil(total / limit) } }); }));
router.get("/songs/:id", asyncHandler(async (req, res) => { const song = await Song.findById(req.params.id); if (!song) throw fail(404, "Song not found"); ok(res, song, "Song fetched"); }));
router.post("/songs", requireAuth, requireAdmin, asyncHandler(async (req, res) => { const song = await Song.create(parse(songSchema, req.body)); ok(res, song, "Song created", 201); }));
router.patch("/songs/:id", requireAuth, requireAdmin, asyncHandler(async (req, res) => { const song = await Song.findByIdAndUpdate(req.params.id, parse(songSchema.partial(), req.body), { new: true, runValidators: true }); if (!song) throw fail(404, "Song not found"); ok(res, song, "Song updated"); }));
router.delete("/songs/:id", requireAuth, requireAdmin, asyncHandler(async (req, res) => { const song = await Song.findByIdAndDelete(req.params.id); if (!song) throw fail(404, "Song not found"); await Promise.all([Like.deleteMany({ song: song._id }), RecentlyPlayed.deleteMany({ song: song._id }), Playlist.updateMany({ songs: song._id }, { $pull: { songs: song._id } })]); ok(res, null, "Song deleted"); }));
router.post("/songs/:id/play", requireAuth, asyncHandler(async (req, res) => { const song = await Song.findByIdAndUpdate(req.params.id, { $inc: { plays: 1 } }, { new: true }); if (!song) throw fail(404, "Song not found"); await recordHistory(req.user._id, song._id); ok(res, song, "Play recorded"); }));
router.post("/songs/:id/like", requireAuth, asyncHandler(async (req, res) => { if (!await Song.exists({ _id: req.params.id })) throw fail(404, "Song not found"); await Like.updateOne({ user: req.user._id, song: req.params.id }, { $setOnInsert: { user: req.user._id, song: req.params.id } }, { upsert: true }); ok(res, { liked: true }, "Song liked"); }));
router.delete("/songs/:id/like", requireAuth, asyncHandler(async (req, res) => { await Like.deleteOne({ user: req.user._id, song: req.params.id }); ok(res, { liked: false }, "Song unliked"); }));
router.get("/songs/:id/like", requireAuth, asyncHandler(async (req, res) => ok(res, { liked: Boolean(await Like.exists({ user: req.user._id, song: req.params.id })) }, "Like status")));

router.get("/albums", asyncHandler(async (_req, res) => ok(res, await Album.find().sort({ createdAt: -1 }), "Albums fetched")));
router.get("/albums/:id", asyncHandler(async (req, res) => { const album = await Album.findById(req.params.id).populate("songs"); if (!album) throw fail(404, "Album not found"); ok(res, album, "Album fetched"); }));
router.get("/artists", asyncHandler(async (_req, res) => ok(res, await Artist.find().sort({ followers: -1 }), "Artists fetched")));
router.get("/artists/:id", asyncHandler(async (req, res) => { const artist = await Artist.findById(req.params.id); if (!artist) throw fail(404, "Artist not found"); const songs = await Song.find({ artist: artist.name }).sort({ plays: -1 }).limit(10); ok(res, { artist, popularSongs: songs, albums: await Album.find({ artist: artist.name }) }, "Artist fetched"); }));
for (const model of [{ path: "artists", Model: Artist }, { path: "albums", Model: Album }]) { router.post(`/${model.path}`, requireAuth, requireAdmin, asyncHandler(async (req, res) => ok(res, await model.Model.create(req.body), `${model.path} created`, 201))); router.patch(`/${model.path}/:id`, requireAuth, requireAdmin, asyncHandler(async (req, res) => { const item = await model.Model.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!item) throw fail(404, "Resource not found"); ok(res, item, "Resource updated"); })); router.delete(`/${model.path}/:id`, requireAuth, requireAdmin, asyncHandler(async (req, res) => { const item = await model.Model.findByIdAndDelete(req.params.id); if (!item) throw fail(404, "Resource not found"); ok(res, null, "Resource deleted"); })); }

router.get("/playlists", asyncHandler(async (req, res) => { const filter = req.user ? { $or: [{ isPublic: true }, { owner: req.user._id }] } : { isPublic: true }; ok(res, await Playlist.find(filter).populate("owner", "fullName imageUrl").sort({ updatedAt: -1 }), "Playlists fetched"); }));
router.get("/playlists/:id", asyncHandler(async (req, res) => { const playlist = await Playlist.findById(req.params.id).populate("owner", "fullName imageUrl").populate("songs"); if (!playlist || (!playlist.isPublic && (!req.user || !ownerOrAdmin(playlist, req.user)))) throw fail(404, "Playlist not found"); ok(res, playlist, "Playlist fetched"); }));
router.post("/playlists", requireAuth, asyncHandler(async (req, res) => ok(res, await Playlist.create({ ...parse(playlistSchema, req.body), owner: req.user._id }), "Playlist created", 201)));
router.patch("/playlists/:id", requireAuth, asyncHandler(async (req, res) => { const playlist = await Playlist.findById(req.params.id); if (!playlist) throw fail(404, "Playlist not found"); if (!ownerOrAdmin(playlist, req.user)) throw fail(403, "You cannot modify this playlist"); Object.assign(playlist, parse(playlistSchema.partial(), req.body)); await playlist.save(); ok(res, playlist, "Playlist updated"); }));
router.delete("/playlists/:id", requireAuth, asyncHandler(async (req, res) => { const playlist = await Playlist.findById(req.params.id); if (!playlist) throw fail(404, "Playlist not found"); if (!ownerOrAdmin(playlist, req.user)) throw fail(403, "You cannot delete this playlist"); await playlist.deleteOne(); ok(res, null, "Playlist deleted"); }));
router.post("/playlists/:id/songs", requireAuth, asyncHandler(async (req, res) => { const playlist = await Playlist.findById(req.params.id); if (!playlist) throw fail(404, "Playlist not found"); if (!ownerOrAdmin(playlist, req.user)) throw fail(403, "You cannot modify this playlist"); const { songId } = parse(z.object({ songId: z.string() }), req.body); if (!await Song.exists({ _id: songId })) throw fail(404, "Song not found"); if (!playlist.songs.some(id => id.toString() === songId)) playlist.songs.push(songId); await playlist.save(); ok(res, playlist, "Song added to playlist"); }));
router.delete("/playlists/:id/songs/:songId", requireAuth, asyncHandler(async (req, res) => { const playlist = await Playlist.findById(req.params.id); if (!playlist) throw fail(404, "Playlist not found"); if (!ownerOrAdmin(playlist, req.user)) throw fail(403, "You cannot modify this playlist"); playlist.songs.pull(req.params.songId); await playlist.save(); ok(res, playlist, "Song removed from playlist"); }));

router.get("/library", requireAuth, asyncHandler(async (req, res) => { const [liked, recent, playlists] = await Promise.all([Like.find({ user: req.user._id }).populate("song"), RecentlyPlayed.find({ user: req.user._id }).sort({ playedAt: -1 }).populate("song"), Playlist.find({ owner: req.user._id })]); ok(res, { likedSongs: liked.map(item => item.song), recentlyPlayed: recent.map(item => item.song), playlists }, "Library fetched"); }));
router.get("/library/liked", requireAuth, asyncHandler(async (req, res) => ok(res, (await Like.find({ user: req.user._id }).populate("song")).map(item => item.song), "Liked songs fetched")));
router.get("/library/recently-played", requireAuth, asyncHandler(async (req, res) => ok(res, await RecentlyPlayed.find({ user: req.user._id }).sort({ playedAt: -1 }).populate("song"), "History fetched")));
router.post("/history/:songId", requireAuth, asyncHandler(async (req, res) => { if (!await Song.exists({ _id: req.params.songId })) throw fail(404, "Song not found"); await recordHistory(req.user._id, req.params.songId); ok(res, null, "History updated"); }));
router.get("/history", requireAuth, asyncHandler(async (req, res) => ok(res, await RecentlyPlayed.find({ user: req.user._id }).sort({ playedAt: -1 }).populate("song"), "History fetched")));
router.delete("/history", requireAuth, asyncHandler(async (req, res) => { await RecentlyPlayed.deleteMany({ user: req.user._id }); ok(res, null, "History cleared"); }));

router.get("/search", asyncHandler(async (req, res) => { const q = parse(z.object({ q: z.string().trim().min(1).max(100) }), req.query).q; const pattern = new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"); const [songs, artists, albums, playlists] = await Promise.all([Song.find({ $or: [{ title: pattern }, { artist: pattern }] }).limit(10), Artist.find({ name: pattern }).limit(10), Album.find({ $or: [{ title: pattern }, { artist: pattern }] }).limit(10), Playlist.find({ isPublic: true, name: pattern }).limit(10)]); ok(res, { songs, artists, albums, playlists }, "Search completed"); }));
router.get("/home", asyncHandler(async (_req, res) => { const [popularSongs, popularAlbums, popularArtists, recommendedPlaylists] = await Promise.all([Song.find().sort({ plays: -1 }).limit(12), Album.find().limit(8), Artist.find().sort({ followers: -1 }).limit(8), Playlist.find({ isPublic: true }).limit(8)]); ok(res, { recentlyPlayed: [], madeForYou: popularSongs.slice(0, 6), popularSongs, popularAlbums, popularArtists, recommendedPlaylists }, "Home content fetched"); }));
router.post("/uploads/:type", requireAuth, requireAdmin, upload.single("file"), asyncHandler(async (req, res) => { if (!req.file) throw fail(400, "A valid audio or image file is required"); if (!process.env.CLOUDINARY_CLOUD_NAME || !process.env.CLOUDINARY_API_KEY || !process.env.CLOUDINARY_API_SECRET) throw fail(503, "Media storage is not configured"); const result = await uploadBuffer(req.file); ok(res, { url: result.secure_url, publicId: result.public_id, resourceType: result.resource_type, bytes: result.bytes }, "Media uploaded", 201); }));
export default router;
