import BeatMusicLogo from "@/components/c/BeatMusicLogo";
import { GitBranch as Github, Mail } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";

export default function AuthPage({ mode }: { mode: "login" | "register" }) {
  const isLogin = mode === "login"; const navigate = useNavigate(); const [submitted, setSubmitted] = useState(false);
  return <main className="grid min-h-screen place-items-center bg-[#121212] p-5 text-white"><section className="w-full max-w-md rounded-2xl bg-[#181818] p-7 shadow-2xl sm:p-9"><div className="mb-8 flex flex-col items-center"><BeatMusicLogo className="size-12" /><h1 className="mt-4 text-center text-3xl font-black">{isLogin ? "Welcome back" : "Create your account"}</h1><p className="mt-2 text-center text-sm text-zinc-400">Continue your sound journey with Beat Music.</p></div><form onSubmit={event => { event.preventDefault(); setSubmitted(true); setTimeout(() => navigate("/home"), 500); }} className="space-y-4">{!isLogin && <label className="block text-sm font-semibold">Name<input required className="mt-2 w-full rounded-md border border-zinc-600 bg-[#242424] p-3 outline-none focus:border-[#22c55e]" placeholder="Your name" /></label>}<label className="block text-sm font-semibold">Email<input required type="email" className="mt-2 w-full rounded-md border border-zinc-600 bg-[#242424] p-3 outline-none focus:border-[#22c55e]" placeholder="name@example.com" /></label><label className="block text-sm font-semibold">Password<input required minLength={6} type="password" className="mt-2 w-full rounded-md border border-zinc-600 bg-[#242424] p-3 outline-none focus:border-[#22c55e]" placeholder="••••••••" /></label>{!isLogin && <label className="block text-sm font-semibold">Confirm password<input required minLength={6} type="password" className="mt-2 w-full rounded-md border border-zinc-600 bg-[#242424] p-3 outline-none focus:border-[#22c55e]" placeholder="••••••••" /></label>}<button className="w-full rounded-full bg-[#22c55e] py-3 font-bold text-black hover:bg-[#3be477]">{submitted ? "Opening your music…" : isLogin ? "Log in" : "Create account"}</button></form>{isLogin && <button className="mt-4 text-sm text-zinc-300 underline">Forgot password?</button>}<div className="my-6 flex items-center gap-3 text-xs text-zinc-500 before:h-px before:flex-1 before:bg-zinc-700 after:h-px after:flex-1 after:bg-zinc-700">OR</div><div className="grid gap-3"><button className="flex items-center justify-center gap-2 rounded-full border border-zinc-600 py-3 text-sm font-bold hover:border-white"><Mail className="size-4" /> Continue with Google</button>{isLogin && <button className="flex items-center justify-center gap-2 rounded-full border border-zinc-600 py-3 text-sm font-bold hover:border-white"><Github className="size-4" /> Continue with GitHub</button>}</div><p className="mt-7 text-center text-sm text-zinc-400">{isLogin ? "New to Beat Music?" : "Already have an account?"} <Link className="font-bold text-white underline" to={isLogin ? "/register" : "/login"}>{isLogin ? "Create account" : "Log in"}</Link></p></section></main>;
}
